# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _mpidplugin
else:
    import _mpidplugin

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import openmm
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mpidplugin.delete_SwigPyIterator

    def value(self):
        return _mpidplugin.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _mpidplugin.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _mpidplugin.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _mpidplugin.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _mpidplugin.SwigPyIterator_equal(self, x)

    def copy(self):
        return _mpidplugin.SwigPyIterator_copy(self)

    def next(self):
        return _mpidplugin.SwigPyIterator_next(self)

    def __next__(self):
        return _mpidplugin.SwigPyIterator___next__(self)

    def previous(self):
        return _mpidplugin.SwigPyIterator_previous(self)

    def advance(self, n):
        return _mpidplugin.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _mpidplugin.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _mpidplugin.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _mpidplugin.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _mpidplugin.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _mpidplugin.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _mpidplugin.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _mpidplugin:
_mpidplugin.SwigPyIterator_swigregister(SwigPyIterator)
class vectord(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mpidplugin.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mpidplugin.vectord___nonzero__(self)

    def __bool__(self):
        return _mpidplugin.vectord___bool__(self)

    def __len__(self):
        return _mpidplugin.vectord___len__(self)

    def __getslice__(self, i, j):
        return _mpidplugin.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mpidplugin.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mpidplugin.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mpidplugin.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mpidplugin.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mpidplugin.vectord___setitem__(self, *args)

    def pop(self):
        return _mpidplugin.vectord_pop(self)

    def append(self, x):
        return _mpidplugin.vectord_append(self, x)

    def empty(self):
        return _mpidplugin.vectord_empty(self)

    def size(self):
        return _mpidplugin.vectord_size(self)

    def swap(self, v):
        return _mpidplugin.vectord_swap(self, v)

    def begin(self):
        return _mpidplugin.vectord_begin(self)

    def end(self):
        return _mpidplugin.vectord_end(self)

    def rbegin(self):
        return _mpidplugin.vectord_rbegin(self)

    def rend(self):
        return _mpidplugin.vectord_rend(self)

    def clear(self):
        return _mpidplugin.vectord_clear(self)

    def get_allocator(self):
        return _mpidplugin.vectord_get_allocator(self)

    def pop_back(self):
        return _mpidplugin.vectord_pop_back(self)

    def erase(self, *args):
        return _mpidplugin.vectord_erase(self, *args)

    def __init__(self, *args):
        _mpidplugin.vectord_swiginit(self, _mpidplugin.new_vectord(*args))

    def push_back(self, x):
        return _mpidplugin.vectord_push_back(self, x)

    def front(self):
        return _mpidplugin.vectord_front(self)

    def back(self):
        return _mpidplugin.vectord_back(self)

    def assign(self, n, x):
        return _mpidplugin.vectord_assign(self, n, x)

    def resize(self, *args):
        return _mpidplugin.vectord_resize(self, *args)

    def insert(self, *args):
        return _mpidplugin.vectord_insert(self, *args)

    def reserve(self, n):
        return _mpidplugin.vectord_reserve(self, n)

    def capacity(self):
        return _mpidplugin.vectord_capacity(self)
    __swig_destroy__ = _mpidplugin.delete_vectord

# Register vectord in _mpidplugin:
_mpidplugin.vectord_swigregister(vectord)
class vectori(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _mpidplugin.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _mpidplugin.vectori___nonzero__(self)

    def __bool__(self):
        return _mpidplugin.vectori___bool__(self)

    def __len__(self):
        return _mpidplugin.vectori___len__(self)

    def __getslice__(self, i, j):
        return _mpidplugin.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _mpidplugin.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _mpidplugin.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _mpidplugin.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _mpidplugin.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _mpidplugin.vectori___setitem__(self, *args)

    def pop(self):
        return _mpidplugin.vectori_pop(self)

    def append(self, x):
        return _mpidplugin.vectori_append(self, x)

    def empty(self):
        return _mpidplugin.vectori_empty(self)

    def size(self):
        return _mpidplugin.vectori_size(self)

    def swap(self, v):
        return _mpidplugin.vectori_swap(self, v)

    def begin(self):
        return _mpidplugin.vectori_begin(self)

    def end(self):
        return _mpidplugin.vectori_end(self)

    def rbegin(self):
        return _mpidplugin.vectori_rbegin(self)

    def rend(self):
        return _mpidplugin.vectori_rend(self)

    def clear(self):
        return _mpidplugin.vectori_clear(self)

    def get_allocator(self):
        return _mpidplugin.vectori_get_allocator(self)

    def pop_back(self):
        return _mpidplugin.vectori_pop_back(self)

    def erase(self, *args):
        return _mpidplugin.vectori_erase(self, *args)

    def __init__(self, *args):
        _mpidplugin.vectori_swiginit(self, _mpidplugin.new_vectori(*args))

    def push_back(self, x):
        return _mpidplugin.vectori_push_back(self, x)

    def front(self):
        return _mpidplugin.vectori_front(self)

    def back(self):
        return _mpidplugin.vectori_back(self)

    def assign(self, n, x):
        return _mpidplugin.vectori_assign(self, n, x)

    def resize(self, *args):
        return _mpidplugin.vectori_resize(self, *args)

    def insert(self, *args):
        return _mpidplugin.vectori_insert(self, *args)

    def reserve(self, n):
        return _mpidplugin.vectori_reserve(self, n)

    def capacity(self):
        return _mpidplugin.vectori_capacity(self)
    __swig_destroy__ = _mpidplugin.delete_vectori

# Register vectori in _mpidplugin:
_mpidplugin.vectori_swigregister(vectori)

import openmm as mm
import openmm.unit as unit

class MPIDForce(openmm.Force):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    NoCutoff = _mpidplugin.MPIDForce_NoCutoff
    PME = _mpidplugin.MPIDForce_PME
    Mutual = _mpidplugin.MPIDForce_Mutual
    Direct = _mpidplugin.MPIDForce_Direct
    Extrapolated = _mpidplugin.MPIDForce_Extrapolated
    ZThenX = _mpidplugin.MPIDForce_ZThenX
    Bisector = _mpidplugin.MPIDForce_Bisector
    ZBisect = _mpidplugin.MPIDForce_ZBisect
    ThreeFold = _mpidplugin.MPIDForce_ThreeFold
    ZOnly = _mpidplugin.MPIDForce_ZOnly
    NoAxisType = _mpidplugin.MPIDForce_NoAxisType
    LastAxisTypeIndex = _mpidplugin.MPIDForce_LastAxisTypeIndex
    Covalent12 = _mpidplugin.MPIDForce_Covalent12
    Covalent13 = _mpidplugin.MPIDForce_Covalent13
    Covalent14 = _mpidplugin.MPIDForce_Covalent14
    PolarizationCovalent11 = _mpidplugin.MPIDForce_PolarizationCovalent11
    PolarizationCovalent12 = _mpidplugin.MPIDForce_PolarizationCovalent12
    PolarizationCovalent13 = _mpidplugin.MPIDForce_PolarizationCovalent13
    PolarizationCovalent14 = _mpidplugin.MPIDForce_PolarizationCovalent14
    CovalentEnd = _mpidplugin.MPIDForce_CovalentEnd

    def __init__(self):
        _mpidplugin.MPIDForce_swiginit(self, _mpidplugin.new_MPIDForce())

    @staticmethod
    def cast(force):
        return _mpidplugin.MPIDForce_cast(force)

    @staticmethod
    def isinstance(force):
        return _mpidplugin.MPIDForce_isinstance(force)

    def getNumMultipoles(self):
        return _mpidplugin.MPIDForce_getNumMultipoles(self)

    def getNonbondedMethod(self):
        return _mpidplugin.MPIDForce_getNonbondedMethod(self)

    def setNonbondedMethod(self, method):
        return _mpidplugin.MPIDForce_setNonbondedMethod(self, method)

    def getPolarizationType(self):
        return _mpidplugin.MPIDForce_getPolarizationType(self)

    def setPolarizationType(self, type):
        return _mpidplugin.MPIDForce_setPolarizationType(self, type)

    def getCutoffDistance(self):
        return _mpidplugin.MPIDForce_getCutoffDistance(self)

    def setCutoffDistance(self, distance):
        return _mpidplugin.MPIDForce_setCutoffDistance(self, distance)

    def getPMEParameters(self):
        return _mpidplugin.MPIDForce_getPMEParameters(self)

    def setPMEParameters(self, alpha, nx, ny, nz):
        return _mpidplugin.MPIDForce_setPMEParameters(self, alpha, nx, ny, nz)

    def getAEwald(self):
        return _mpidplugin.MPIDForce_getAEwald(self)

    def setAEwald(self, aewald):
        return _mpidplugin.MPIDForce_setAEwald(self, aewald)

    def getPmeBSplineOrder(self):
        return _mpidplugin.MPIDForce_getPmeBSplineOrder(self)

    def getPmeGridDimensions(self):
        return _mpidplugin.MPIDForce_getPmeGridDimensions(self)

    def setPmeGridDimensions(self, gridDimension):
        return _mpidplugin.MPIDForce_setPmeGridDimensions(self, gridDimension)

    def getPMEParametersInContext(self, context):
        return _mpidplugin.MPIDForce_getPMEParametersInContext(self, context)

    def addMultipole(self, charge, molecularDipole, molecularQuadrupole, molecularOctopole, axisType, multipoleAtomZ, multipoleAtomX, multipoleAtomY, thole, alphas):
        return _mpidplugin.MPIDForce_addMultipole(self, charge, molecularDipole, molecularQuadrupole, molecularOctopole, axisType, multipoleAtomZ, multipoleAtomX, multipoleAtomY, thole, alphas)

    def getMultipoleParameters(self, index):
        return _mpidplugin.MPIDForce_getMultipoleParameters(self, index)

    def setMultipoleParameters(self, index, charge, molecularDipole, molecularQuadrupole, molecularOctopole, axisType, multipoleAtomZ, multipoleAtomX, multipoleAtomY, thole, alphas):
        return _mpidplugin.MPIDForce_setMultipoleParameters(self, index, charge, molecularDipole, molecularQuadrupole, molecularOctopole, axisType, multipoleAtomZ, multipoleAtomX, multipoleAtomY, thole, alphas)

    def setCovalentMap(self, index, typeId, covalentAtoms):
        return _mpidplugin.MPIDForce_setCovalentMap(self, index, typeId, covalentAtoms)

    def getCovalentMap(self, index, typeId):
        return _mpidplugin.MPIDForce_getCovalentMap(self, index, typeId)

    def getCovalentMaps(self, index, covalentLists):
        return _mpidplugin.MPIDForce_getCovalentMaps(self, index, covalentLists)

    def getMutualInducedMaxIterations(self):
        return _mpidplugin.MPIDForce_getMutualInducedMaxIterations(self)

    def setMutualInducedMaxIterations(self, inputMutualInducedMaxIterations):
        return _mpidplugin.MPIDForce_setMutualInducedMaxIterations(self, inputMutualInducedMaxIterations)

    def getMutualInducedTargetEpsilon(self):
        return _mpidplugin.MPIDForce_getMutualInducedTargetEpsilon(self)

    def setMutualInducedTargetEpsilon(self, inputMutualInducedTargetEpsilon):
        return _mpidplugin.MPIDForce_setMutualInducedTargetEpsilon(self, inputMutualInducedTargetEpsilon)

    def set14ScaleFactor(self, val):
        return _mpidplugin.MPIDForce_set14ScaleFactor(self, val)

    def get14ScaleFactor(self):
        return _mpidplugin.MPIDForce_get14ScaleFactor(self)

    def setExtrapolationCoefficients(self, coefficients):
        return _mpidplugin.MPIDForce_setExtrapolationCoefficients(self, coefficients)

    def getExtrapolationCoefficients(self):
        return _mpidplugin.MPIDForce_getExtrapolationCoefficients(self)

    def getEwaldErrorTolerance(self):
        return _mpidplugin.MPIDForce_getEwaldErrorTolerance(self)

    def setEwaldErrorTolerance(self, tol):
        return _mpidplugin.MPIDForce_setEwaldErrorTolerance(self, tol)

    def getLabFramePermanentDipoles(self, context):
        return _mpidplugin.MPIDForce_getLabFramePermanentDipoles(self, context)

    def getInducedDipoles(self, context):
        return _mpidplugin.MPIDForce_getInducedDipoles(self, context)

    def getTotalDipoles(self, context):
        return _mpidplugin.MPIDForce_getTotalDipoles(self, context)

    def getElectrostaticPotential(self, inputGrid, context):
        return _mpidplugin.MPIDForce_getElectrostaticPotential(self, inputGrid, context)

    def getSystemMultipoleMoments(self, context):
        return _mpidplugin.MPIDForce_getSystemMultipoleMoments(self, context)

    def updateParametersInContext(self, context):
        return _mpidplugin.MPIDForce_updateParametersInContext(self, context)

    def usesPeriodicBoundaryConditions(self):
        return _mpidplugin.MPIDForce_usesPeriodicBoundaryConditions(self)

    def setDefaultTholeWidth(self, val):
        return _mpidplugin.MPIDForce_setDefaultTholeWidth(self, val)

    def getDefaultTholeWidth(self):
        return _mpidplugin.MPIDForce_getDefaultTholeWidth(self)
    __swig_destroy__ = _mpidplugin.delete_MPIDForce

# Register MPIDForce in _mpidplugin:
_mpidplugin.MPIDForce_swigregister(MPIDForce)

import openmm.app.forcefield as forcefield
import warnings

## @private
class MPIDGenerator(object):

#=============================================================================================

    """A MPIDGenerator constructs a MPIDForce."""

#=============================================================================================

    def __init__(self, forceField, scaleFactor14, defaultTholeWidth):
        self.forceField = forceField
        self.scaleFactor14 = scaleFactor14
        self.defaultTholeWidth = defaultTholeWidth
        self.typeMap = {}

#=============================================================================================
# Set axis type
#=============================================================================================

    @staticmethod
    def setAxisType(kIndices):

# set axis type

                kIndicesLen = len(kIndices)

                if (kIndicesLen > 3):
                    ky = kIndices[3]
                    kyNegative = False
                    if ky.startswith('-'):
                        ky = kIndices[3] = ky[1:]
                        kyNegative = True
                else:
                    ky = ""

                if (kIndicesLen > 2):
                    kx = kIndices[2]
                    kxNegative = False
                    if kx.startswith('-'):
                        kx = kIndices[2] = kx[1:]
                        kxNegative = True
                else:
                    kx = ""

                if (kIndicesLen > 1):
                    kz = kIndices[1]
                    kzNegative = False
                    if kz.startswith('-'):
                        kz = kIndices[1] = kz[1:]
                        kzNegative = True
                else:
                    kz = ""

                while(len(kIndices) < 4):
                    kIndices.append("")

                axisType = MPIDForce.ZThenX
                if (not kz):
                    axisType = MPIDForce.NoAxisType
                if (kz and not kx):
                    axisType = MPIDForce.ZOnly
                if (kz and kzNegative or kx and kxNegative):
                    axisType = MPIDForce.Bisector
                if (kx and kxNegative and ky and kyNegative):
                    axisType = MPIDForce.ZBisect
                if (kz and kzNegative and kx and kxNegative and ky and kyNegative):
                    axisType = MPIDForce.ThreeFold

                return axisType

#=============================================================================================

    @staticmethod
    def parseElement(element, forceField):

#   <MPIDForce >
# <Multipole class="1"    kz="2"    kx="4"    c0="-0.22620" d1="0.08214" d2="0.00000" d3="0.34883" q11="0.11775" q21="0.00000" q22="-1.02185" q31="-0.17555" q32="0.00000" q33="0.90410"  />
# <Multipole class="2"    kz="1"    kx="3"    c0="-0.15245" d1="0.19517" d2="0.00000" d3="0.19687" q11="-0.20677" q21="0.00000" q22="-0.48084" q31="-0.01672" q32="0.00000" q33="0.68761"  />

        existing = [f for f in forceField._forces if isinstance(f, MPIDGenerator)]
        if len(existing) == 0:
            generator = MPIDGenerator(forceField, element.get('coulomb14scale', None), element.get('defaultTholeWidth', None))
            forceField.registerGenerator(generator)
        else:
# Multiple <MPIDForce> tags were found, probably in different files.  Simply add more types to the existing one.
            generator = existing[0]
            if abs(generator.scaleFactor14 != element.get('coulomb14scale', None)):
                raise ValueError('Found multiple MPIDForce tags with different coulomb14scale arguments')
            if abs(generator.defaultTholeWidth != element.get('defaultTholeWidth', None)):
                raise ValueError('Found multiple MPIDForce tags with different defaultTholeWidth arguments')

# set type map: [ kIndices, multipoles, AMOEBA/OpenMM axis type]

        for atom in element.findall('Multipole'):
            types = forceField._findAtomTypes(atom.attrib, 1)
            if None not in types:

# k-indices not provided default to 0

                kIndices = [atom.attrib['type']]

                kStrings = [ 'kz', 'kx', 'ky' ]
                for kString in kStrings:
                    try:
                        if (atom.attrib[kString]):
                             kIndices.append(atom.attrib[kString])
                    except:
                        pass

# set axis type based on k-Indices

                axisType = MPIDGenerator.setAxisType(kIndices)

# set multipole

                charge = float(atom.get('c0'))

                conversion = 1.0
                dipole = [ conversion*float(atom.get('dX', 0.0)),
                           conversion*float(atom.get('dY', 0.0)),
                           conversion*float(atom.get('dZ', 0.0)) ]

                quadrupole = []
                quadrupole.append(conversion*float(atom.get('qXX', 0.0)))
                quadrupole.append(conversion*float(atom.get('qXY', 0.0)))
                quadrupole.append(conversion*float(atom.get('qYY', 0.0)))
                quadrupole.append(conversion*float(atom.get('qXZ', 0.0)))
                quadrupole.append(conversion*float(atom.get('qYZ', 0.0)))
                quadrupole.append(conversion*float(atom.get('qZZ', 0.0)))

                octopole = []
                octopole.append(conversion*float(atom.get('oXXX', 0.0)))
                octopole.append(conversion*float(atom.get('oXXY', 0.0)))
                octopole.append(conversion*float(atom.get('oXYY', 0.0)))
                octopole.append(conversion*float(atom.get('oYYY', 0.0)))
                octopole.append(conversion*float(atom.get('oXXZ', 0.0)))
                octopole.append(conversion*float(atom.get('oXYZ', 0.0)))
                octopole.append(conversion*float(atom.get('oYYZ', 0.0)))
                octopole.append(conversion*float(atom.get('oXZZ', 0.0)))
                octopole.append(conversion*float(atom.get('oYZZ', 0.0)))
                octopole.append(conversion*float(atom.get('oZZZ', 0.0)))

                for t in types[0]:
                    if (t not in generator.typeMap):
                        generator.typeMap[t] = []

                    valueMap = dict()
                    valueMap['classIndex'] = atom.attrib['type']
                    valueMap['kIndices'] = kIndices
                    valueMap['charge'] = charge
                    valueMap['dipole'] = dipole
                    valueMap['quadrupole'] = quadrupole
                    valueMap['octopole'] = octopole
                    valueMap['axisType'] = axisType
                    generator.typeMap[t].append(valueMap)

            else:
                outputString = "MPIDGenerator: error getting type for multipole: %s" % (atom.attrib['class'])
                raise ValueError(outputString)

# polarization parameters

        for atom in element.findall('Polarize'):
            types = forceField._findAtomTypes(atom.attrib, 1)
            if None not in types:

                classIndex = atom.attrib['type']
                polarizability = [ float(atom.attrib['polarizabilityXX']),
                                   float(atom.attrib['polarizabilityYY']),
                                   float(atom.attrib['polarizabilityZZ']) ]
                thole = float(atom.attrib['thole'])

                for t in types[0]:
                    if (t not in generator.typeMap):
                        outputString = "MPIDGenerator: polarize type not present: %s" % (atom.attrib['type'])
                        raise ValueError(outputString)
                    else:
                        typeMapList = generator.typeMap[t]
                        hit = 0
                        for (ii, typeMap) in enumerate(typeMapList):

                            if (typeMap['classIndex'] == classIndex):
                                typeMap['polarizability'] = polarizability
                                typeMap['thole'] = thole
                                typeMapList[ii] = typeMap
                                hit = 1

                        if (hit == 0):
                            outputString = "MPIDGenerator: error getting type for polarize: class index=%s not in multipole list?" % (atom.attrib['class'])
                            raise ValueError(outputString)

            else:
                outputString = "MPIDGenerator: error getting type for polarize: %s" % (atom.attrib['class'])
                raise ValueError(outputString)

#=============================================================================================

    def createForce(self, sys, data, nonbondedMethod, nonbondedCutoff, args):

        methodMap = {forcefield.NoCutoff:MPIDForce.NoCutoff,
                     forcefield.PME:MPIDForce.PME,
                     forcefield.LJPME:MPIDForce.PME}

        force = MPIDForce()
        sys.addForce(force)
        if (nonbondedMethod not in methodMap):
            raise ValueError( "MPIDForce: input cutoff method not available." )
        else:
            force.setNonbondedMethod(methodMap[nonbondedMethod])
        force.setCutoffDistance(nonbondedCutoff)

        if ('ewaldErrorTolerance' in args):
            force.setEwaldErrorTolerance(float(args['ewaldErrorTolerance']))

        force.setPolarizationType(MPIDForce.Extrapolated)
        if ('polarization' in args):
            polarizationType = args['polarization']
            if (polarizationType.lower() == 'direct'):
                force.setPolarizationType(MPIDForce.Direct)
            elif (polarizationType.lower() == 'mutual'):
                force.setPolarizationType(MPIDForce.Mutual)
            elif (polarizationType.lower() == 'extrapolated'):
                force.setPolarizationType(MPIDForce.Extrapolated)
            else:
                raise ValueError( "MPIDForce: invalide polarization type: " + polarizationType)

        argval = float(args['coulomb14scale']) if 'coulomb14scale' in args else None
        myval = float(self.scaleFactor14) if self.scaleFactor14 else None
        if argval is not None:
            if myval is not None:
                if myval != argval:
                     warnings.warn( "Conflicting coulomb14scale values found in forcefield file ({}) and createSystem args ({}).  "
                                    "Using the value from createSystem's arguments".format(myval, argval))
            force.set14ScaleFactor(argval)
        else:
            if myval is not None:
                force.set14ScaleFactor(myval)

        argval = float(args['defaultTholeWidth']) if 'defaultTholeWidth' in args else None
        myval = float(self.defaultTholeWidth) if self.defaultTholeWidth else None
        if argval is not None:
            if myval is not None:
                if myval != argval:
                     warnings.warn( "Conflicting defaultTholeWidth values found in forcefield file ({}) and createSystem args ({}).  "
                                    "Using the value from createSystem's arguments".format(myval, argval))
            force.setDefaultTholeWidth(argval)
        else:
            if myval is not None:
                force.setDefaultTholeWidth(myval)

        if ('aEwald' in args):
            force.setAEwald(float(args['aEwald']))

        if ('pmeGridDimensions' in args):
            force.setPmeGridDimensions(args['pmeGridDimensions'])

        if ('mutualInducedMaxIterations' in args):
            force.setMutualInducedMaxIterations(int(args['mutualInducedMaxIterations']))

        if ('mutualInducedTargetEpsilon' in args):
            force.setMutualInducedTargetEpsilon(float(args['mutualInducedTargetEpsilon']))

# add particles to force
# throw error if particle type not available

# get 1-2, 1-3, 1-4, 1-5 bonded sets

# 1-2

        if hasattr(forcefield.AmoebaVdwGenerator, 'getBondedParticleSets'):
            bonded12ParticleSets = forcefield.AmoebaVdwGenerator.getBondedParticleSets(sys, data)
        else:
# OpenMM 8.x: use topology-derived bonded list from ForceField._SystemData.
            bonded12ParticleSets = [set(x) for x in data.bondedToAtom]

# 1-3

        bonded13ParticleSets = []
        for i in range(len(data.atoms)):
            bonded13Set = set()
            bonded12ParticleSet = bonded12ParticleSets[i]
            for j in bonded12ParticleSet:
                bonded13Set = bonded13Set.union(bonded12ParticleSets[j])

# remove 1-2 and self from set

            bonded13Set = bonded13Set - bonded12ParticleSet
            selfSet = set()
            selfSet.add(i)
            bonded13Set = bonded13Set - selfSet
            bonded13Set = set(sorted(bonded13Set))
            bonded13ParticleSets.append(bonded13Set)

# 1-4

        bonded14ParticleSets = []
        for i in range(len(data.atoms)):
            bonded14Set = set()
            bonded13ParticleSet = bonded13ParticleSets[i]
            for j in bonded13ParticleSet:
                bonded14Set = bonded14Set.union(bonded12ParticleSets[j])

# remove 1-3, 1-2 and self from set

            bonded14Set = bonded14Set - bonded12ParticleSets[i]
            bonded14Set = bonded14Set - bonded13ParticleSet
            selfSet = set()
            selfSet.add(i)
            bonded14Set = bonded14Set - selfSet
            bonded14Set = set(sorted(bonded14Set))
            bonded14ParticleSets.append(bonded14Set)


        for (atomIndex, atom) in enumerate(data.atoms):
            t = data.atomType[atom]
            if t in self.typeMap:

                multipoleList = self.typeMap[t]
                hit = 0
                savedMultipoleDict = 0

# assign multipole parameters via only 1-2 connected atoms

                for multipoleDict in multipoleList:

                    if (hit != 0):
                        break

                    kIndices = multipoleDict['kIndices']

                    kz = kIndices[1]
                    kx = kIndices[2]
                    ky = kIndices[3]

# assign multipole parameters
#    (1) get bonded partners
#    (2) match parameter types

                    bondedAtomIndices = bonded12ParticleSets[atomIndex]
                    zaxis = -1
                    xaxis = -1
                    yaxis = -1
                    for bondedAtomZIndex in bondedAtomIndices:

                       if (hit != 0):
                           break

                       bondedAtomZType = data.atomType[data.atoms[bondedAtomZIndex]]
                       bondedAtomZ = data.atoms[bondedAtomZIndex]
                       if (bondedAtomZType == kz):
                          for bondedAtomXIndex in bondedAtomIndices:
                              if (bondedAtomXIndex == bondedAtomZIndex or hit != 0):
                                  continue
                              bondedAtomXType = data.atomType[data.atoms[bondedAtomXIndex]]
                              if (bondedAtomXType == kx):
                                  if (not ky):
                                      zaxis = bondedAtomZIndex
                                      xaxis = bondedAtomXIndex
                                      if( bondedAtomXType == bondedAtomZType and xaxis < zaxis ):
                                          swapI = zaxis
                                          zaxis = xaxis
                                          xaxis = swapI
                                      else:
                                          for bondedAtomXIndex in bondedAtomIndices:
                                              bondedAtomX1Type = data.atomType[data.atoms[bondedAtomXIndex]]
                                              if( bondedAtomX1Type == kx and bondedAtomXIndex != bondedAtomZIndex and bondedAtomXIndex < xaxis ):
                                                  xaxis = bondedAtomXIndex

                                      savedMultipoleDict = multipoleDict
                                      hit = 1
                                  else:
                                      for bondedAtomYIndex in bondedAtomIndices:
                                          if (bondedAtomYIndex == bondedAtomZIndex or bondedAtomYIndex == bondedAtomXIndex or hit != 0):
                                              continue
                                          bondedAtomYType = data.atomType[data.atoms[bondedAtomYIndex]]
                                          if (bondedAtomYType == ky):
                                              zaxis = bondedAtomZIndex
                                              xaxis = bondedAtomXIndex
                                              yaxis = bondedAtomYIndex
                                              savedMultipoleDict = multipoleDict
                                              hit = 2

# assign multipole parameters via 1-2 and 1-3 connected atoms

                for multipoleDict in multipoleList:

                    if (hit != 0):
                        break

                    kIndices = multipoleDict['kIndices']

                    kz = kIndices[1]
                    kx = kIndices[2]
                    ky = kIndices[3]

# assign multipole parameters
#    (1) get bonded partners
#    (2) match parameter types

                    bondedAtom12Indices = bonded12ParticleSets[atomIndex]
                    bondedAtom13Indices = bonded13ParticleSets[atomIndex]

                    zaxis = -1
                    xaxis = -1
                    yaxis = -1

                    for bondedAtomZIndex in bondedAtom12Indices:

                       if (hit != 0):
                           break

                       bondedAtomZType = data.atomType[data.atoms[bondedAtomZIndex]]
                       bondedAtomZ = data.atoms[bondedAtomZIndex]

                       if (bondedAtomZType == kz):
                          for bondedAtomXIndex in bondedAtom13Indices:

                              if (bondedAtomXIndex == bondedAtomZIndex or hit != 0):
                                  continue
                              bondedAtomXType = data.atomType[data.atoms[bondedAtomXIndex]]
                              if (bondedAtomXType == kx and bondedAtomZIndex in bonded12ParticleSets[bondedAtomXIndex]):
                                  if (not ky):
                                      zaxis = bondedAtomZIndex
                                      xaxis = bondedAtomXIndex

# select xaxis w/ smallest index

                                      for bondedAtomXIndex in bondedAtom13Indices:
                                          bondedAtomX1Type = data.atomType[data.atoms[bondedAtomXIndex]]
                                          if( bondedAtomX1Type == kx and bondedAtomXIndex != bondedAtomZIndex and bondedAtomZIndex in bonded12ParticleSets[bondedAtomXIndex] and bondedAtomXIndex < xaxis ):
                                              xaxis = bondedAtomXIndex

                                      savedMultipoleDict = multipoleDict
                                      hit = 3
                                  else:
                                      for bondedAtomYIndex in bondedAtom13Indices:
                                          if (bondedAtomYIndex == bondedAtomZIndex or bondedAtomYIndex == bondedAtomXIndex or hit != 0):
                                              continue
                                          bondedAtomYType = data.atomType[data.atoms[bondedAtomYIndex]]
                                          if (bondedAtomYType == ky and bondedAtomZIndex in bonded12ParticleSets[bondedAtomYIndex]):
                                              zaxis = bondedAtomZIndex
                                              xaxis = bondedAtomXIndex
                                              yaxis = bondedAtomYIndex
                                              savedMultipoleDict = multipoleDict
                                              hit = 4

# assign multipole parameters via only a z-defining atom

                for multipoleDict in multipoleList:

                    if (hit != 0):
                        break

                    kIndices = multipoleDict['kIndices']

                    kz = kIndices[1]
                    kx = kIndices[2]

                    zaxis = -1
                    xaxis = -1
                    yaxis = -1

                    for bondedAtomZIndex in bondedAtom12Indices:

                        if (hit != 0):
                            break

                        bondedAtomZType = data.atomType[data.atoms[bondedAtomZIndex]]
                        bondedAtomZ = data.atoms[bondedAtomZIndex]

                        if (not kx and kz == bondedAtomZType):
                            zaxis = bondedAtomZIndex
                            savedMultipoleDict = multipoleDict
                            hit = 5

# assign multipole parameters via no connected atoms

                for multipoleDict in multipoleList:

                    if (hit != 0):
                        break

                    kIndices = multipoleDict['kIndices']

                    kz = kIndices[1]

                    zaxis = -1
                    xaxis = -1
                    yaxis = -1

                    if (not kz):
                        savedMultipoleDict = multipoleDict
                        hit = 6

# add particle if there was a hit

                if (hit != 0):

                    atom.multipoleDict = savedMultipoleDict
                    atom.polarizationGroups = dict()
                    try:
                        thole = savedMultipoleDict['thole']
                    except KeyError:
                        thole = 0.0
                    try:
                        polarizability = savedMultipoleDict['polarizability']
                    except KeyError:
                        polarizability = [0.0, 0.0, 0.0]

                    newIndex = force.addMultipole(savedMultipoleDict['charge'], savedMultipoleDict['dipole'],
                                                  savedMultipoleDict['quadrupole'], savedMultipoleDict['octopole'], savedMultipoleDict['axisType'],
                                                  zaxis, xaxis, yaxis, thole, polarizability)
                    if (atomIndex == newIndex):
                        force.setCovalentMap(atomIndex, MPIDForce.Covalent12, tuple(bonded12ParticleSets[atomIndex]))
                        force.setCovalentMap(atomIndex, MPIDForce.Covalent13, tuple(bonded13ParticleSets[atomIndex]))
                        force.setCovalentMap(atomIndex, MPIDForce.Covalent14, tuple(bonded14ParticleSets[atomIndex]))
                    else:
                        raise ValueError("Atom %s of %s %d is out of sync!." %(atom.name, atom.residue.name, atom.residue.index))
                else:
                    raise ValueError("Atom %s of %s %d was not assigned." %(atom.name, atom.residue.name, atom.residue.index))
            else:
                raise ValueError('No multipole type for atom %s %s %d' % (atom.name, atom.residue.name, atom.residue.index))

forcefield.parsers["MPIDForce"] = MPIDGenerator.parseElement


